### ISSUE TITLE
Permission to use

### ISSUE THREAD

**Issue by pHiney** [simongarisch/qstyles#3]
Not sure what you licence or usage is. 
Can I use this for python Path of Building
https://github.com/pHiney/PathOfBuilding-Python/

**Comment by simongarisch** [comment]
@pHiney Happy for you to use in whatever way you find useful. I'd originally included an MIT license in the repo. Whilst I've written the Python code, those style sheets are collected from a variety of other repos and I've endeavored to include an original link and license at the top of each sheet. Happy coding.
